"""Shim: re-export RBAC models from derisk-ext to avoid duplicate table definitions."""

from derisk_ext.plugin.auth.rbac.models import (
    AGENT_ACTIONS,
    GroupRoleEntity,
    KNOWLEDGE_ACTIONS,
    MODEL_ACTIONS,
    PermissionDefinitionEntity,
    RESOURCE_ACTIONS,
    RESOURCE_AGENT,
    RESOURCE_KNOWLEDGE,
    RESOURCE_MODEL,
    RESOURCE_SYSTEM,
    RESOURCE_TOOL,
    RoleEntity,
    RolePermissionDefEntity,
    RolePermissionEntity,
    TOOL_ACTIONS,
    UserGroupEntity,
    UserGroupMemberEntity,
    UserRoleEntity,
)

__all__ = [
    "AGENT_ACTIONS",
    "GroupRoleEntity",
    "KNOWLEDGE_ACTIONS",
    "MODEL_ACTIONS",
    "PermissionDefinitionEntity",
    "RESOURCE_ACTIONS",
    "RESOURCE_AGENT",
    "RESOURCE_KNOWLEDGE",
    "RESOURCE_MODEL",
    "RESOURCE_SYSTEM",
    "RESOURCE_TOOL",
    "RoleEntity",
    "RolePermissionDefEntity",
    "RolePermissionEntity",
    "TOOL_ACTIONS",
    "UserGroupEntity",
    "UserGroupMemberEntity",
    "UserRoleEntity",
]
